---
title: "trains-data"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(jsonlite)
library(httr)
library(rvest)
library(readxl)
library(tidyverse)
library(mdsr)   
library(tidyr)
library(ggplot2)
library(readr)
library(knitr)
```

## NYC data

```{r, message=FALSE}
# Functions to clean up files for each folder:
# clean 'calendar.txt' files
calendar_clean_data <- function(file_name) {
  df <- read_csv(file_name) 
  return(df)
}

# clean 'routes.txt' files
routes_clean_data <- function(file_name) {
  df <- read_csv(file_name) %>% 
    select(route_id) 
  return(df)
}

# clean 'shapes.txt' files
shapes_clean_data <- function(file_name) {
  df <- read_csv(file_name) %>% 
    select(shape_dist_traveled, shape_id) 
  return(df)
}

# clean 'stop_times.txt' files
stop_times_clean_data <- function(file_name) {
  df <- read_csv(file_name) %>% 
    select(trip_id, arrival_time, departure_time, stop_id,
                 shape_dist_traveled) 
  return(df)
}

# clean 'stops.txt' files
stops_clean_data <- function(file_name) {
  df <- read_csv(file_name) %>% 
    select(stop_id, stop_name, zone_id) 
  return(df)
}

# clean 'trips.txt' files
trips_clean_data <- function(file_name) {
  df <- read_csv(file_name) %>% 
    select(route_id, service_id, trip_id, shape_id) 
  return(df)
}


calendar <- calendar_clean_data('nyc/2013-10-30-nyc/calendar.txt')
routes <- routes_clean_data('nyc/2013-10-30-nyc/routes.txt')
shapes <- shapes_clean_data('nyc/2013-10-30-nyc/shapes.txt')
stop_times <- stop_times_clean_data('nyc/2013-10-30-nyc/stop_times.txt')
stops <- stops_clean_data('nyc/2013-10-30-nyc/stops.txt')
trips <- trips_clean_data('nyc/2013-10-30-nyc/trips.txt')


calendar_clean_data <- function(file_name) {
  
}

calendar_dates_clean_data <- function(file_name) {
  
}
```