---
title: "census-data"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(jsonlite)
library(httr)
library(rvest)
library(readxl)
library(tidyverse)
library(mdsr)   
library(tidyr)
library(ggplot2)
library(readr)
library(knitr)
```

## OLD DATA

```{r, message=False}
# HC03_VC134 (percent no health insurance coverage)
# HC03_VC171 (percentage of people with income below poverty level)

# clean up data frames from 2007-2009
# (the census changed variable names after 2009)
data_2007_2009 <- function(file_name, year) {
  df <- read_csv(file_name) %>% 
    mutate('Median household income (dollars)' = HC01_EST_VC69,
           'Percent workers commuting by public transportation' = HC02_EST_VC23,
           'Percent population unemployed' = HC02_EST_VC06,
           'Year' = year) %>% 
     select(Year, GEO.id, GEO.id2, `GEO.display-label`, 
           `Median household income (dollars)`, 
           `Percent workers commuting by public transportation`,
           `Percent population unemployed`)
            
  return(df)
}

# clean up data frames from 2010-2017
data_2010_2017 <- function(file_name, year) {
  df <- read_csv(file_name) %>% 
    mutate('Median household income (dollars)' = HC01_VC85,
           'Percent workers commuting by public transportation' = HC03_VC31,
           'Percent population unemployed' = HC03_VC08,
           'Percent no health insurance coverage' = HC03_VC134,
          
            # for all people 18 years and older:
           'Percent income below poverty level' = HC03_VC171,
           'Year' = year ) %>% 
     select(Year, GEO.id, GEO.id2, `GEO.display-label`, 
           `Median household income (dollars)`, 
           `Percent workers commuting by public transportation`,
           `Percent population unemployed`,
           `Percent no health insurance coverage`,
           `Percent income below poverty level`)
            
  return(df)
}

census_2007 <- data_2007_2009("2007/ACS_07_1YR_DP3.csv", 2007)
census_2008 <- data_2007_2009("2008/ACS_08_1YR_DP3.csv", 2008)
census_2009 <- data_2007_2009("2009/ACS_09_1YR_DP3.csv", 2009)
  
census_2010 <- data_2010_2017("2010/ACS_10_1YR_DP03.csv", 2010)
census_2011 <- data_2010_2017("2011/ACS_11_1YR_DP03.csv", 2011)
census_2012 <- data_2010_2017("2012/ACS_12_1YR_DP03.csv", 2012)
census_2013 <- data_2010_2017("2013/ACS_13_1YR_DP03.csv", 2013)
census_2014 <- data_2010_2017("2014/ACS_14_1YR_DP03.csv", 2014)
census_2015 <- data_2010_2017("2015/ACS_15_1YR_DP03.csv", 2015)
census_2016 <- data_2010_2017("2016/ACS_16_1YR_DP03.csv", 2016)
census_2017 <- data_2010_2017("2017/ACS_17_1YR_DP03.csv", 2017)

final_census_df <- full_join(census_2007, census_2008) %>% 
  full_join(census_2009) %>% 
  full_join(census_2010) %>% 
  full_join(census_2011) %>% 
  full_join(census_2012) %>% 
  full_join(census_2013) %>% 
  full_join(census_2014) %>% 
  full_join(census_2015) %>% 
  full_join(census_2016) %>% 
  full_join(census_2017)
  # separate(col = City, into = c("City","State"), sep = ",", remove = TRUE)

View(final_census_df)

# need to fix geo.display-label column

```

```{r}
variablecsv <- read_csv("2007/ACS_07_1YR_DP3_ann.csv")
View(variablecsv)
```

## NEW DATA
```{r}
data_2007_2009 <- function(file_name, year) {
  df <- read_csv(file_name) %>% 
    mutate('Pop 16 years and over' = HC01_EST_VC02,
           'Pop 16 years and over, in labor force, civilian labor force, employed' = HC01_EST_VC05,
           'Workers 16 years and over, commuting to work' = HC01_EST_VC20,
           'Workers 16 years and over, commuting to work, public transport' = HC01_EST_VC23,
           'Percent income below poverty level - all people' = HC01_EST_VC112,
           'Year' = year) %>% 
    
     select(Year, GEO.id, GEO.id2, `GEO.display-label`, 
           `Pop 16 years and over`,
           `Pop 16 years and over, in labor force, civilian labor force, employed`,
           `Workers 16 years and over, commuting to work`,
           `Workers 16 years and over, commuting to work, public transport`,
           `Percent income below poverty level - all people`, 
           `Year`)
    
  return(df)
}
```

```{r}
# clean up data frames from 2010-2017
data_2010_2017 <- function(file_name, year) {
    df <- read_csv(file_name) %>% 
    mutate('Pop 16 years and over' = 'HC01_VC04,Estimate',
           'Pop 16 years and over, in labor force, civilian labor force, employed' = 'HC01_EST_VC05,Estimate',
           'Workers 16 years and over, commuting to work' = 'HC01_VC20,Estimate',
           'Workers 16 years and over, commuting to work, public transport' = 'HC01_VC23,Estimate',
            'Percent income below poverty level - all people' = 'HC01_VC112,Estimate',
           'Year' = year,
           'Civilian noninstitutionalized pop' = HC01_VC130,
           'Civilian noninstitutionalized pop with health insurance' = HC01_VC131) %>% 
    
     select(Year, GEO.id, GEO.id2, `GEO.display-label`,
           `Pop 16 years and over`,
           `Pop 16 years and over, in labor force, civilian labor force, employed`,
           `Workers 16 years and over, commuting to work`,
           `Workers 16 years and over, commuting to work, public transport`,
           `Percent income below poverty level - all people`, 
           `Year`,
           `Civilian noninstitutionalized pop`,
           `Civilian noninstitutionalized pop with health insurance`)
  return(df)
}

```


```{r}


census_2007 <- data_2007_2009("2007/ACS_07_1YR_DP3.csv", 2007)
census_2008 <- data_2007_2009("2008/ACS_08_1YR_DP3.csv", 2008)
census_2009 <- data_2007_2009("2009/ACS_09_1YR_DP3.csv", 2009)
  
census_2010 <- data_2010_2017("2010/ACS_10_1YR_DP03.csv", 2010)
census_2011 <- data_2010_2017("2011/ACS_11_1YR_DP03.csv", 2011)
census_2012 <- data_2010_2017("2012/ACS_12_1YR_DP03.csv", 2012)
census_2013 <- data_2010_2017("2013/ACS_13_1YR_DP03.csv", 2013)
census_2014 <- data_2010_2017("2014/ACS_14_1YR_DP03.csv", 2014)
census_2015 <- data_2010_2017("2015/ACS_15_1YR_DP03.csv", 2015)
census_2016 <- data_2010_2017("2016/ACS_16_1YR_DP03.csv", 2016)
census_2017 <- data_2010_2017("2017/ACS_17_1YR_DP03.csv", 2017)

final_census_df <- full_join(census_2007, census_2008) %>% 
  full_join(census_2009) %>% 
  full_join(census_2010) %>% 
  full_join(census_2011) %>% 
  full_join(census_2012) %>% 
  full_join(census_2013) %>% 
  full_join(census_2014) %>% 
  full_join(census_2015) %>% 
  full_join(census_2016) %>% 
  full_join(census_2017)
  # separate(col = City, into = c("City","State"), sep = ",", remove = TRUE)

View(final_census_df)
```

