---
title: "gdp-data"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(jsonlite)
library(httr)
library(rvest)
library(readxl)
library(tidyverse)
library(mdsr)   
library(tidyr)
library(ggplot2)
library(readr)
library(knitr)
```

## Import Data

```{r, message = FALSE}
gdp_df <- read_xls("gdp-industrytotal.xls", sheet = 1, 
                      range = 'A6:S390', col_names=TRUE) %>% 
  gather(key = "Year", value = "gdp", -c("GeoFips", "GeoName")) %>% 
  mutate("GEO.id2" = as.integer(GeoFips), "Year" = as.double(Year)) %>% 
  select(GEO.id2, GeoName, Year, gdp) 


  # separate(col = GeoName, into = c("City","State"), sep = ",", remove = TRUE)
  #sapply(FUN = gsub(pattern = "(Metropolitan Statistical Area)",
                                                  #   replacement = "", x = "(Metropolitan Statistical Area)"))

View(gdp_df)

#  select(State)

#file_name <- paste0('States', '.csv')
#write.csv(test, file_name, row.names=T)
```

