---
title: "joined-data"
output: html_document
---

## Set up
```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(jsonlite)
library(httr)
library(rvest)
library(readxl)
library(tidyverse)
library(mdsr)   
library(tidyr)
library(ggplot2)
library(readr)
library(knitr)
```

## Join Census Data
```{r, message=FALSE}

data_pop <- pop_all_years
data_census <- final_census_df
data_gdp <- gdp_df
data_coord <- coord_df

data_joined_pop_census <- left_join(data_pop, data_census, by = c("Year", "GEO.id", "GEO.id2", "GEO.display-label"))

data_joined_pop_census_gdp <- left_join(data_joined_pop_census, data_gdp, by = c("GEO.id2", "Year"))

quality_of_life_df <- left_join(data_joined_pop_census_gdp, coord_df, by = c("GEO.id2", "GEO.display-label")) %>% 
  select(-c(GEO.id, GeoName))

```

```{r}
transit_data <- FTA_df

#Join final transit and quality of life datasets and
#Filter out non-urban areas 
FINAL_DF <- left_join(quality_of_life_df, transit_data, by=c("GEO.id2", "Year")) %>% 
  filter(UA != 99999) %>% 
  mutate(gdp = gdp*1000000)
 
  
#clarify variables names
  colnames(FINAL_DF)[1:28] <- c("msa_id", 
                               "msa_name", 
                               "pop_estimate_msa", 
                               "year", 
                               "median_household_income_msa",
                               "percent_workers_commuting_by_public_transit_msa",
                               "percent_unemployed_msa",
                               "percent_no_insurance_msa",
                               "percent_below_poverty_level",
                               "gdp_msa",
                               "centlat",
                               "centlon",
                               "intptlat",
                               "intptlon",
                               "ua_census_id",
                               "ua_pop_2010",
                               "ua_sq_miles_2010",
                               "ua_fta_name",
                               "transit_modes",
                               "passenger_trips",
                               "vehicle_miles",
                               "vehicle_hours",
                               "total_stations_2017",
                               "total_funding",
                               "federal_funding",
                               "state_funding",
                               "local_funding",
                               "other_funding")
                               
  



```
