---
title: "gdp-data"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(jsonlite)
library(httr)
library(rvest)
library(readxl)
library(tidyverse)
library(mdsr)   
library(tidyr)
library(ggplot2)
library(readr)
library(knitr)
```

## Import Data

```{r, message = FALSE}

unemployment_df <- function(sheet_number, year) {
  df <- read_xlsx("bls-unemployment.xlsx", sheet=sheet_number,
                          range='A1:C52', col_names=TRUE) 
  colnames(df)[2] <- "Rate" 
  df <- df[-c(1),]
  df <- df %>% 
    mutate("Year" = year)
  return(df)
}

unemployment_2013 <- unemployment_df(1, 2013)
unemployment_2014 <- unemployment_df(2, 2014)
unemployment_2015 <- unemployment_df(3, 2015)
unemployment_2016 <- unemployment_df(4, 2016)
unemployment_2017 <- unemployment_df(5, 2017)

final_unemployment_df <- full_join(unemployment_2013, unemployment_2014) %>% 
  full_join(unemployment_2015) %>% 
  full_join(unemployment_2016) %>% 
  full_join(unemployment_2017) %>% 
  separate(col = City, into = c("City","State"), sep = ",", remove = TRUE)

head(final_unemployment_df)

```

## Works Cited
https://stackoverflow.com/questions/12328056/how-do-i-delete-rows-in-a-data-frame to find out how to delete a row in a dataframe